"""add employee profile fields

Revision ID: 26176c04d988
Revises: ff2a7f5a759d
Create Date: 2026-10-03 22:08:50.539002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26176c04d988'
down_revision: Union[str, Sequence[str], None] = 'ff2a7f5a759d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('designation', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('joining_date', sa.Date(), nullable=True))
    op.add_column(
    'employees',
    sa.Column(
        'employment_status',
        sa.String(),
        nullable=False,
        server_default='ACTIVE'
    )
    )
    op.add_column('employees', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('emergency_contact_name', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('emergency_contact_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'emergency_contact_phone')
    op.drop_column('employees', 'emergency_contact_name')
    op.drop_column('employees', 'phone')
    op.drop_column('employees', 'employment_status')
    op.drop_column('employees', 'joining_date')
    op.drop_column('employees', 'designation')
    # ### end Alembic commands ###
