"""add manager relationship

Revision ID: 58cb0c16ed7f
Revises: d5d8d3e0964d
Create Date: 2026-09-20 10:30:20.887903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58cb0c16ed7f'
down_revision: Union[str, Sequence[str], None] = 'd5d8d3e0964d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
