"""create leave policies table

Revision ID: ac1b339e0b58
Revises: 7bdbcf2ca420
Create Date: 2026-09-20 09:47:51.720132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1b339e0b58'
down_revision: Union[str, Sequence[str], None] = '7bdbcf2ca420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(), nullable=False),
    sa.Column('annual_days', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_policies_id'), 'leave_policies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_policies_id'), table_name='leave_policies')
    op.drop_table('leave_policies')
    # ### end Alembic commands ###
