"""add reusable invitation link fields

Revision ID: b68574512e4a
Revises: 71ff49a3865b
Create Date: 2026-10-10 19:02:20.022754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b68574512e4a'
down_revision: Union[str, Sequence[str], None] = '71ff49a3865b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('max_uses', sa.Integer(), nullable=True))
    op.add_column('invitations', sa.Column('uses_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('invitations', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('invitations', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    op.alter_column('invitations', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(
    "fk_invitations_created_by_users",
    "invitations",
    "users",
    ["created_by"],
    ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
    "fk_invitations_created_by_users",
    "invitations",
    type_="foreignkey"
    )
    op.alter_column('invitations', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('invitations', 'revoked_at')
    op.drop_column('invitations', 'created_by')
    op.drop_column('invitations', 'uses_count')
    op.drop_column('invitations', 'max_uses')
    # ### end Alembic commands ###
