"""add manager to employees

Revision ID: d5d8d3e0964d
Revises: ac1b339e0b58
Create Date: 2026-09-20 10:22:12.354249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d8d3e0964d'
down_revision: Union[str, Sequence[str], None] = 'ac1b339e0b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'employees', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'manager_id')
    # ### end Alembic commands ###
