"""add employee lifecycle fields

Revision ID: fc4147ac3c86
Revises: 84a7bcdf78a7
Create Date: 2026-10-03 23:03:41.391951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4147ac3c86'
down_revision: Union[str, Sequence[str], None] = '84a7bcdf78a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('leaving_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('termination_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'termination_reason')
    op.drop_column('employees', 'leaving_date')
    # ### end Alembic commands ###
