"""add hr and employee hr relationship

Revision ID: ff2a7f5a759d
Revises: 58cb0c16ed7f
Create Date: 2026-10-02 23:15:31.206421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2a7f5a759d'
down_revision: Union[str, Sequence[str], None] = '58cb0c16ed7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hrs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hrs_email'), 'hrs', ['email'], unique=True)
    op.create_index(op.f('ix_hrs_id'), 'hrs', ['id'], unique=False)
    op.add_column('employees', sa.Column('hr_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
    'fk_employees_hr_id',
    'employees',
    'hrs',
    ['hr_id'],
    ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
    'fk_employees_hr_id',
    'employees',
    type_='foreignkey'
)
    op.drop_column('employees', 'hr_id')
    op.drop_index(op.f('ix_hrs_id'), table_name='hrs')
    op.drop_index(op.f('ix_hrs_email'), table_name='hrs')
    op.drop_table('hrs')
    # ### end Alembic commands ###
